on:
  push:
  workflow_dispatch:

env:
  ENVIRONMENT_TYPE: nonprod

name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: nonprod
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resource Group
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az version
          az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}

    - name: Preview Changes from Bicep
      uses: Azure/deployment-what-if-action@v1.0.0
      with:
        templateFile: ./main.bicep
        subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroup: ${{ vars.RESOURCE_GROUP_NAME }}
        parametersFile: ./main.parameters.${{ env.ENVIRONMENT_TYPE }}.json
        # additionalParameters: environmentType=${{ env.ENVIRONMENT_TYPE }}

    - name: Request approval
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Deploy Azure Bicep resources',
            head: context.sha,
            base: 'main',
          });
          await github.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pullRequest.number,
            reviewers: ['rodmhgl', ],
          });

    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.30.0
    #     inlineScript: |
    #       az group delete --yes --name ${{ vars.RESOURCE_GROUP_NAME }} --only-show-errors
    #       az group create --name ${{ vars.RESOURCE_GROUP_NAME }} --location ${{ vars.RESOURCE_GROUP_LOCATION }}

    #   # Deploy Bicep file
    # - name: deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
    #     template: ./main.bicep
    #     parameters: ./main.parameters.${{ENVIRONMENT}}.json
    #     # parameters: 'environmentType=nonprod'
    #     failOnStdErr: false
